name: Main Workflow

on:
  push:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/
    - run: npm i
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    - run: npm run lint

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/
    - run: npm i
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    - run: npm run test
