name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - uses: actions/checkout@v4
      - run: npm i --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: npm run build
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
